---
name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: rusty-actions/sam-code-signing-config/.github/workflows/test.yml@main

  action:
    name: Build and release action
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: bump the version
        id: bumper
        uses: tomerfi/version-bumper-action@1.2.1

      - name: Update README major version
        id: version_count
        run: echo "count=$(fgrep -c sam-code-signing-config@v${{ steps.bumper.outputs.major_part }} README.md)" >> $GITHUB_OUTPUT

      - name: Update README usage example
        if: steps.version_count.outputs.count == 0
        run: |
          sed -i 's|uses\: rusty-actions/sam-code-signing-config@.*|uses\: rusty-actions/sam-code-signing-config@v${{ steps.bumper.outputs.major_part }}|g' README.md

      - name: Configure git
        if: steps.version_count.outputs.count == 0
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push modifications
        if: steps.version_count.outputs.count == 0
        run: |
          if [[ ! $(git diff --quiet) ]]; then
            git add README.md
            git commit -m "docs: update README usage section with v${{ steps.bumper.outputs.major_part }} [skip ci]"
            git push
          fi

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.bumper.outputs.new_version }}

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ steps.bumper.outputs.new_version }}
